// kevinarmstrong.io Cloudflare Worker
//
// Two responsibilities:
//   1. Block obvious recon paths (/.env, /admin, /backup.sql, etc.) — same as
//      the previous worker.
//   2. Wrap every successful response with a consistent set of security
//      headers, so they live in HTTP response headers (reportable) instead of
//      a per-page <meta> tag.
//
// The Content-Security-Policy migration is staged. Today the CSP is shipped as
// `Content-Security-Policy-Report-Only` so we can observe browser violation
// reports without breaking the site. The existing <meta http-equiv> tag in
// index.html remains the *enforced* policy. Once the inline-script-hash work
// (pen-test 2026-05-05 KA-2026-05-05-01) lands and we have a clean violation
// log for ~7 days, the next PR flips this header to `Content-Security-Policy`
// (enforced) and removes the <meta> tag.

// Build-time-computed sha256 hashes for every inline <script> block on the
// site (data islands like JSON-LD and the RSS-seed). Generated by
// scripts/compute_csp_hashes.py and refreshed daily by .github/workflows/
// rss.yml after the RSS sync. See pen-test 2026-05-05 finding KA-01.
import { CSP_INLINE_SCRIPT_HASHES } from "./_worker_csp_hashes.js";

const BLOCKED_PATHS = new Set([
  '/.env',
  '/.htpasswd',
  '/.htaccess',
  '/.ds_store',
  '/settings.py',
  '/config.php',
  '/phpinfo.php',
  '/info.php',
  '/server-status',
  '/server-info',
  '/debug',
  '/trace.axd',
  '/elmah.axd',
  '/thumbs.db',
  '/backup.sql',
  '/database.sql',
  '/dump.sql',
  '/admin',
  '/account',
  '/dashboard',
  '/billing',
  '/api/admin',
  '/api/private',
  '/api/users',
  '/api/settings',
  '/api/docs',
  '/config',
  '/internal',
  '/manage',
  '/orders',
  '/payments',
  '/profile',
  '/settings',
  '/users',
  '/swagger.json',
  '/openapi.json',
  '/graphql',
]);

const BLOCKED_PREFIXES = ['/.git/', '/.env.', '/debug/'];

function isBlocked(pathname) {
  const p = pathname.toLowerCase();
  if (BLOCKED_PATHS.has(p)) return true;
  for (const prefix of BLOCKED_PREFIXES) {
    if (p.startsWith(prefix)) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Security headers
// ---------------------------------------------------------------------------

// CSP — single source of truth, enforced by the Worker.
//
// History:
//   - Pre-2026-05-05: CSP shipped as a <meta http-equiv> tag inside index.html
//     and 404.html, with 'unsafe-inline' in script-src to support inline
//     blocks (JSON-LD, RSS-seed, blog watchdog, RSS-list toggle).
//   - PR #23 (2026-05-05): Worker added a Content-Security-Policy-Report-Only
//     header that mirrored the meta tag, so the migration from meta -> header
//     could be staged.
//   - PR #24: externalised the two executable inline scripts (blog-loading
//     watchdog and RSS-list toggle) to same-origin .js files, so the only
//     remaining inline <script> content is non-executable data islands
//     (JSON-LD org schema, RSS-seed JSON, per-post JSON-LD).
//   - PR #25: introduced scripts/compute_csp_hashes.py and the
//     auto-generated _worker_csp_hashes.js, so each remaining inline data
//     island is permitted by exact sha256 hash without needing
//     'unsafe-inline'. Refreshed daily by .github/workflows/rss.yml.
//   - PR #26 (this commit): flips the Worker to ENFORCE the strict policy
//     (no 'unsafe-inline' on script-src) and removes the now-redundant
//     <meta http-equiv> tag from index.html and 404.html.
//
// Pen-test 2026-05-05 finding KA-2026-05-05-01 — RESOLVED.
const _CSP_BASE = [
  "default-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self' data:",
  "img-src 'self' data: blob: https:",
  "connect-src 'self' " +
    "https://*.supabase.co " +
    "https://api.allorigins.win " +
    "https://r.jina.ai " +
    "https://gist.githubusercontent.com " +
    "https://gistcdn.githack.com " +
    "https://kevinarmstrong.goatcounter.com " +
    "https://gc.zgo.at",
  "frame-src 'self' https://www.loom.com",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self' https://buy.stripe.com https://calendar.app.google https://*.supabase.co",
  "frame-ancestors 'none'",
];

// KA-2026-05-15-01: name of the reporting group used by `report-to` and
// `Reporting-Endpoints`. The Worker handles the corresponding POST path
// (CSP_REPORT_PATH below) and emits the violation report to the Worker
// log (wrangler tail / Cloudflare Logpush), so CSP regressions surface as
// 204s in the access log instead of disappearing silently in the browser.
const CSP_REPORT_GROUP = 'csp-endpoint';
const CSP_REPORT_PATH = '/api/csp-report';

const CONTENT_SECURITY_POLICY = [
  ..._CSP_BASE,
  // No 'unsafe-inline' here. PR #25 will join in the build-time-computed
  // sha256 hash list (one per remaining inline <script> data island) and
  // splice it into this directive.
  // Strict script-src for the report-only (and eventually enforced) policy.
  // Splices in the build-time-computed hash list so legitimate inline
  // <script type="application/ld+json"> / <script type="application/json">
  // data islands and per-blog JSON-LD blobs are permitted by exact-content
  // hash without needing 'unsafe-inline'.
  ["script-src 'self' https://cdn.jsdelivr.net https://gc.zgo.at"]
    .concat(CSP_INLINE_SCRIPT_HASHES)
    .join(" "),
  // KA-2026-05-15-01: telemetry directives. `report-to` is the modern
  // Reporting API directive (named group below); `report-uri` is the
  // legacy directive kept for older browsers (Safari < 16.4 / Firefox
  // < 110). Both point at the same first-party endpoint handled by this
  // Worker so a misbehaving extension or compromised CDN does not also
  // get to drop violation telemetry on the floor.
  `report-uri ${CSP_REPORT_PATH}`,
  `report-to ${CSP_REPORT_GROUP}`,
].join('; ');

// Other security headers — flat object so headers can be merged into the
// upstream response in one pass without overwriting the asset's Content-Type
// or Cache-Control.
const SECURITY_HEADERS = {
  // 2 years, includeSubDomains, preload — closes WA-2026-05-05-04 equivalent
  // for kevinarmstrong.io. Submit to hstspreload.org once this has been live
  // for one full max-age window.
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy':
    'camera=(), microphone=(), geolocation=(), interest-cohort=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  // KA-2026-05-13-02: Cross-Origin-Embedder-Policy: credentialless.
  // Pairs with the existing COOP: same-origin to put HTML documents into a
  // cross-origin isolated context, which (a) hardens against Spectre-style
  // cross-origin side-channel attacks on shared-memory features and (b)
  // surfaces accidental loading of cross-origin subresources without
  // explicit opt-in (CORP / CORS). We pick 'credentialless' rather than
  // 'require-corp' because the only third-party subresource the document
  // currently pulls (gc.zgo.at analytics beacon) does not return a CORP
  // header today; 'credentialless' strips ambient cookies on that hop
  // instead of blocking it outright. If/when every cross-origin
  // dependency advertises a CORP header, this can be tightened to
  // 'require-corp'.
  'Cross-Origin-Embedder-Policy': 'credentialless',
  // KA-2026-05-12-04: add Cross-Origin-Resource-Policy. Same-origin matches
  // the existing COOP posture and prevents cross-origin sites from
  // embedding our subresources cross-credentialed. CORP defaults to
  // 'cross-origin' for static-CDN-served images on Cloudflare Pages, but
  // because the site only serves first-party assets the tighter value is
  // safe today and surfaces accidental cross-origin embedding regressions
  // immediately.
  'Cross-Origin-Resource-Policy': 'same-origin',
  // X-XSS-Protection: explicitly disable legacy browser XSS auditor.
  // Modern guidance (OWASP Secure Headers Project) recommends setting
  // this to 0 so that older Chromium/IE/Safari versions do not attempt
  // their built-in heuristic XSS filter — which has produced more bypass
  // vectors over the years than it has prevented. The strict CSP above
  // is the live XSS defense.
  'X-XSS-Protection': '0',
  // KA-2026-05-15-01: Reporting-Endpoints header is the modern Reporting
  // API counterpart to the CSP `report-to` directive. Named group must match
  // CSP_REPORT_GROUP above. The Worker accepts violation POSTs at
  // CSP_REPORT_PATH and logs them; production reports are visible via
  // `wrangler tail` and Cloudflare Logpush. See compliance/csp-reporting.md.
  'Reporting-Endpoints': `${CSP_REPORT_GROUP}="${CSP_REPORT_PATH}"`,
  // Enforced. The strict policy (no 'unsafe-inline' on script-src)
  // is now the live security boundary; the meta tag has been removed from
  // index.html and 404.html in this PR.
  'Content-Security-Policy': CONTENT_SECURITY_POLICY,
};

// Only attach security headers to HTML / SVG document responses. Static
// assets (CSS, JS, images, fonts) inherit upstream caching headers and don't
// need CSP — and adding HSTS to a 304 / opaque response can confuse some
// clients.
function isHtmlResponse(response) {
  const ct = response.headers.get('content-type') || '';
  return (
    ct.includes('text/html') ||
    ct.includes('application/xhtml+xml') ||
    ct.includes('image/svg+xml') ||
    ct === ''
  );
}

function withSecurityHeaders(response) {
  // Always set HSTS — it's a domain-level signal, not document-specific.
  // CSP and document-only headers gate on isHtmlResponse() to avoid noise.
  const headers = new Headers(response.headers);
  headers.set(
    'Strict-Transport-Security',
    SECURITY_HEADERS['Strict-Transport-Security'],
  );
  headers.set('X-Content-Type-Options', SECURITY_HEADERS['X-Content-Type-Options']);

  if (isHtmlResponse(response)) {
    for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
      headers.set(name, value);
    }
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

// ---------------------------------------------------------------------------
// Worker entrypoint
// ---------------------------------------------------------------------------

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // KA-2026-05-15-01: accept CSP / Reporting-API violation reports.
    // We accept both the legacy application/csp-report body and the
    // modern application/reports+json batch body. The handler logs and
    // returns 204; we deliberately do NOT persist payloads here because
    // Worker isolates are stateless — the access log + wrangler tail are
    // the persistent record. Method is locked to POST; GET / OPTIONS
    // return 405 / 204 so the path cannot be used to enumerate the
    // Worker. Bodies over 64 KiB are truncated to keep log lines bounded.
    if (url.pathname === CSP_REPORT_PATH) {
      if (request.method === 'OPTIONS') {
        return new Response(null, {
          status: 204,
          headers: { 'Allow': 'POST', 'Cache-Control': 'no-store' },
        });
      }
      if (request.method !== 'POST') {
        return new Response('Method Not Allowed', {
          status: 405,
          headers: { 'Allow': 'POST', 'Cache-Control': 'no-store' },
        });
      }
      try {
        const text = await request.text();
        const truncated = text.length > 65536 ? text.slice(0, 65536) + '…[truncated]' : text;
        // Single-line log entry so Cloudflare Logpush can ingest it as JSON.
        console.log(JSON.stringify({
          kind: 'csp-report',
          ua: request.headers.get('user-agent') || '',
          ct: request.headers.get('content-type') || '',
          body: truncated,
        }));
      } catch (_e) {
        // Swallow — never let a malformed report turn into a 5xx.
      }
      return new Response(null, { status: 204, headers: { 'Cache-Control': 'no-store' } });
    }

    if (isBlocked(url.pathname)) {
      return new Response('Not Found', { status: 404 });
    }

    const response = await env.ASSETS.fetch(request);

    if (response.status !== 404) {
      return withSecurityHeaders(response);
    }

    // True 404 for unknown paths: serve the dedicated 404 page with HTTP
    // status 404 so search engines deindex the URL and users see a clear
    // "Page Not Found" message instead of the homepage.
    //
    // Cloudflare Pages auto-strips `.html` and 308-redirects /404.html
    // -> /404, so we fetch the canonical /404 path here. Daily-audit
    // 2026-05-06 NAV-05.
    const notFoundResponse = await env.ASSETS.fetch(
      new Request(new URL('/404', url.origin), request),
    );
    return withSecurityHeaders(
      new Response(notFoundResponse.body, {
        status: 404,
        headers: notFoundResponse.headers,
      }),
    );
  },
};
