#!/usr/bin/env python3
"""
Compute sha256 CSP hashes for every inline <script> block in the site.

Run from the repo root:

    python3 scripts/compute_csp_hashes.py

It walks `index.html`, every `blog/*/index.html`, every `goingvegan/*/index.html`,
and any other top-level entrypoints, finds every `<script>...</script>` block
that has NO `src=` attribute, sha256-hashes the content **byte-exact** as it
appears in the file, and writes the deduplicated, sorted list to:

    _worker_csp_hashes.js

That file is imported by `_worker.js` and joined into the
`Content-Security-Policy-Report-Only` (and eventually `Content-Security-Policy`)
header's `script-src` directive. Because Cloudflare Pages bakes the worker at
build time, the hash list is read once per deploy — exactly as fast as a
constant.

This script is run by `.github/workflows/rss.yml` after the daily RSS sync
regenerates `index.html`'s RSS-seed block (which mutates the hash and would
otherwise drift from the worker's allowlist).

Pen-test 2026-05-05 finding KA-2026-05-05-01.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import re
import sys
from pathlib import Path

# Match a <script ...>...</script> block. We use a non-greedy body so adjacent
# blocks don't merge. We capture the attributes string and the body separately
# so we can skip blocks that have a `src=` attribute (those are external
# references and don't need hashing).
SCRIPT_RE = re.compile(
    r"<script(?P<attrs>[^>]*)>(?P<body>.*?)</script>",
    re.IGNORECASE | re.DOTALL,
)
SRC_ATTR_RE = re.compile(r"\bsrc\s*=", re.IGNORECASE)


def find_html_files(repo_root: Path) -> list[Path]:
    """All HTML files we want to scan. Tightly scoped — no audits/, no test/."""
    candidates: list[Path] = []
    for top in (
        "index.html",
        "404.html",
    ):
        p = repo_root / top
        if p.exists():
            candidates.append(p)
    for sub in ("blog", "goingvegan", "booking", "privacy", "terms-and-conditions"):
        d = repo_root / sub
        if d.is_dir():
            candidates.extend(d.rglob("*.html"))
    # De-dupe but preserve order
    seen, out = set(), []
    for p in candidates:
        if p in seen:
            continue
        seen.add(p)
        out.append(p)
    return out


def hash_inline_scripts(html: str) -> list[str]:
    """Return the CSP `'sha256-<base64>'` token for every inline script block."""
    hashes: list[str] = []
    for m in SCRIPT_RE.finditer(html):
        attrs = m.group("attrs") or ""
        if SRC_ATTR_RE.search(attrs):
            continue  # external <script src="...">
        body = m.group("body")
        # CSP hashes are computed over the EXACT bytes between <script> and
        # </script>, not stripped, normalised, or unescaped. The browser does
        # the same. (https://www.w3.org/TR/CSP3/#external-hash)
        digest = hashlib.sha256(body.encode("utf-8")).digest()
        b64 = base64.b64encode(digest).decode("ascii")
        hashes.append(f"'sha256-{b64}'")
    return hashes


def write_worker_module(repo_root: Path, hashes: list[str]) -> Path:
    """Emit `_worker_csp_hashes.js` exporting an alphabetically-sorted array."""
    out = repo_root / "_worker_csp_hashes.js"
    sorted_unique = sorted(set(hashes))
    body_lines = [
        "// AUTOGENERATED by scripts/compute_csp_hashes.py — do not hand-edit.",
        "//",
        "// CSP sha256 hashes for every inline <script> block on the site.",
        "// Imported by _worker.js and joined into the script-src directive.",
        "//",
        f"// Last regenerated for {len(sorted_unique)} unique blocks across the site.",
        "//",
        "// Pen-test 2026-05-05 finding KA-2026-05-05-01.",
        "",
        "export const CSP_INLINE_SCRIPT_HASHES = [",
    ]
    for h in sorted_unique:
        # Each hash is already wrapped in single quotes; wrap the JS string
        # literal in double quotes to keep escaping simple.
        body_lines.append(f'  "{h}",')
    body_lines.append("];")
    body_lines.append("")
    out.write_text("\n".join(body_lines), encoding="utf-8")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root (defaults to the parent of scripts/).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Exit non-zero if _worker_csp_hashes.js would change. Use in CI to "
            "fail fast when a developer edits an inline <script> without "
            "rerunning this script."
        ),
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    files = find_html_files(repo_root)
    if not files:
        print("ERROR: no HTML files found", file=sys.stderr)
        return 2

    all_hashes: list[str] = []
    per_file: dict[str, int] = {}
    for f in files:
        html = f.read_text(encoding="utf-8")
        hs = hash_inline_scripts(html)
        if hs:
            per_file[str(f.relative_to(repo_root))] = len(hs)
        all_hashes.extend(hs)

    out = repo_root / "_worker_csp_hashes.js"
    if args.check:
        # Recompute what we WOULD write and diff it against the existing file.
        sorted_unique = sorted(set(all_hashes))
        new_blob_lines = []
        for h in sorted_unique:
            new_blob_lines.append(f'  "{h}",')
        existing = out.read_text(encoding="utf-8") if out.exists() else ""
        # Compare only the array contents (ignore comment/header churn).
        existing_hashes = sorted(
            re.findall(r"'sha256-[A-Za-z0-9+/=]+'", existing)
        )
        if existing_hashes != sorted_unique:
            print(
                "FAIL: _worker_csp_hashes.js is out of date.\n"
                f"  expected {len(sorted_unique)} hashes,"
                f" found {len(existing_hashes)}.\n"
                f"  Regenerate: python3 scripts/compute_csp_hashes.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: _worker_csp_hashes.js up to date ({len(sorted_unique)} hashes)")
        return 0

    out_path = write_worker_module(repo_root, all_hashes)
    print(
        f"wrote {out_path.relative_to(repo_root)}"
        f" — {len(set(all_hashes))} unique hashes"
        f" across {sum(per_file.values())} inline blocks"
        f" in {len(per_file)} files"
    )
    # Per-file breakdown for the commit message
    for fname, n in sorted(per_file.items()):
        print(f"  {n:4d}  {fname}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
